const $=id=>document.getElementById(id);const safe=u=>u&&u!=='#'?u:'#';
function button(x){const a=document.createElement('a');a.className=`button ${x.primary?'button-primary':''}`;a.href=safe(x.url);a.textContent=x.label;if(x.url&&x.url!=='#'){a.target='_blank';a.rel='noopener'}return a}
function bg(el,img){if(el&&img)el.style.backgroundImage=`linear-gradient(135deg,rgba(120,20,30,.28),transparent 55%),url("${img}")`;el?.querySelector('span')?.remove()}
function render(){
 const hs=$('heroSocials'),sg=$('socialGrid'),fl=$('footerLinks');
 CONFIG.socials.forEach(s=>{let i=document.createElement('a');i.className='icon-link';i.href=safe(s.url);i.textContent=s.short;i.title=s.name;if(s.url!=='#'){i.target='_blank';i.rel='noopener'}hs.appendChild(i);let c=document.createElement('a');c.className='social-card';c.href=safe(s.url);c.innerHTML=`<span class="social-mark">${s.short}</span><span><strong>${s.name}</strong><small>Visitar perfil oficial</small></span>`;if(s.url!=='#'){c.target='_blank';c.rel='noopener'}sg.appendChild(c);let f=document.createElement('a');f.href=safe(s.url);f.textContent=s.name;if(s.url!=='#'){f.target='_blank';f.rel='noopener'}fl.appendChild(f)});
 $('flagshipTitle').textContent=CONFIG.flagship.title;$('flagshipTitle2').textContent=CONFIG.flagship.title;$('flagshipSubtitle').textContent=CONFIG.flagship.subtitle;$('flagshipDescription').textContent=CONFIG.flagship.description;bg($('flagshipImage'),CONFIG.flagship.image);CONFIG.flagship.links.forEach(x=>$('flagshipButtons').appendChild(button(x)));
 $('latestTitle').textContent=CONFIG.latest.title;$('latestDescription').textContent=CONFIG.latest.description;bg($('latestImage'),CONFIG.latest.image);CONFIG.latest.links.forEach(x=>$('latestButtons').appendChild(button(x)));
 $('albumTitle').textContent=CONFIG.album.title;$('albumTitle2').textContent=CONFIG.album.title;$('albumDescription').textContent=CONFIG.album.description;$('albumText').textContent=CONFIG.album.text;bg($('albumImage'),CONFIG.album.image);CONFIG.album.links.forEach(x=>$('albumButtons').appendChild(button(x)));
 CONFIG.venas.singles.forEach(s=>{let a=document.createElement('a');a.className='mini-single';a.href=safe(s.url);a.textContent=s.title;if(s.url!=='#'){a.target='_blank';a.rel='noopener'}$('obsidianSingles').appendChild(a)});$('operaButton').href=safe(CONFIG.venas.fullOperaUrl);$('year').textContent=new Date().getFullYear()
}
const mb=document.querySelector('.menu-button'),mm=document.querySelector('.mobile-menu');mb.addEventListener('click',()=>{let o=mm.classList.toggle('open');mb.setAttribute('aria-expanded',o)});document.querySelectorAll('.mobile-menu a').forEach(a=>a.onclick=()=>mm.classList.remove('open'));render();
